apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - kustomizeconfig.yaml

resources:
  - deployment.yaml
  - route.yaml
  - service.yaml

vars:
- name: ROUTE_SERVICE
  objref:
    kind: Service
    name: simple-rsyslog
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name

images:
- name: quay.io/pflaeging/simple-rsyslog
  newName: image-registry.openshift-image-registry.svc:5000/develop/simple-rsyslog
  newTag: latest